package logging

import "fmt"

// Generated by https://patorjk.com/software/taag/#p=testall&f=Isometric4&t=Holistic
// Thanks to https://github.com/patorjk for providing such a great tool
func Logo() {
	Delimiter()
	fmt.Print(Bold)
	fmt.Println(Red + `      ___     ` + Yellow + `      ___     ` + Green + `      ___ ` + Blue + `            ` + Purple + `      ___      ` + Cyan + `     ___     ` + Red + `            ` + Green + `      ___      `)
	fmt.Println(Red + `     /\__\    ` + Yellow + `     /\  \    ` + Green + `     /\__\` + Blue + `      ___   ` + Purple + `     /\  \     ` + Cyan + `    /\  \    ` + Red + `      ___   ` + Green + `     /\  \     `)
	fmt.Println(Red + `    /:/  /    ` + Yellow + `    /::\  \   ` + Green + `    /:/  /` + Blue + `     /\  \  ` + Purple + `    /::\  \    ` + Cyan + `    \:\  \   ` + Red + `     /\  \  ` + Green + `    /::\  \    `)
	fmt.Println(Red + `   /:/__/     ` + Yellow + `   /:/\:\  \  ` + Green + `   /:/  / ` + Blue + `     \:\  \ ` + Purple + `   /:/\ \  \   ` + Cyan + `     \:\  \  ` + Red + `     \:\  \ ` + Green + `   /:/\:\  \   `)
	fmt.Println(Red + `  /::\  \ ___ ` + Yellow + `  /:/  \:\  \ ` + Green + `  /:/  /  ` + Blue + `     /::\__\` + Purple + `  _\:\~\ \  \  ` + Cyan + `     /::\  \ ` + Red + `     /::\__\` + Green + `  /:/  \:\  \  `)
	fmt.Println(Red + ` /:/\:\  /\__\` + Yellow + ` /:/__/ \:\__\` + Green + ` /:/__/   ` + Blue + `  __/:/\/__/` + Purple + ` /\ \:\ \ \__\ ` + Cyan + `    /:/\:\__\` + Red + `  __/:/\/__/` + Green + ` /:/__/ \:\__\ `)
	fmt.Println(Red + ` \/__\:\/:/  /` + Yellow + ` \:\  \ /:/  /` + Green + ` \:\  \   ` + Blue + ` /\/:/  /   ` + Purple + ` \:\ \:\ \/__/ ` + Cyan + `   /:/  \/__/` + Red + ` /\/:/  /   ` + Green + ` \:\  \  \/__/ `)
	fmt.Println(Red + `      \::/  / ` + Yellow + `  \:\  /:/  / ` + Green + `  \:\  \  ` + Blue + ` \::/__/    ` + Purple + `  \:\ \:\__\   ` + Cyan + `  /:/  /     ` + Red + ` \::/__/    ` + Green + `  \:\  \       `)
	fmt.Println(Red + `      /:/  /  ` + Yellow + `   \:\/:/  /  ` + Green + `   \:\  \ ` + Blue + `  \:\__\    ` + Purple + `   \:\/:/  /   ` + Cyan + `  \/__/      ` + Red + `  \:\__\    ` + Green + `   \:\  \      `)
	fmt.Println(Red + `     /:/  /   ` + Yellow + `    \::/  /   ` + Green + `    \:\__\` + Blue + `   \/__/    ` + Purple + `    \::/  /    ` + Cyan + `             ` + Red + `   \/__/    ` + Green + `    \:\__\     `)
	fmt.Println(Red + `     \/__/    ` + Yellow + `     \/__/    ` + Green + `     \/__/` + Blue + `            ` + Purple + `     \/__/     ` + Cyan + `             ` + Red + `            ` + Green + `     \/__/     ` + Reset)
	Delimiter()
}
